# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 972eabc9ce1f7aa6d950a64e63c178412029753abdc2152b5cd67786a8bb26e400d7f2ad3654829e6d5b51c3235d06e324660d2586ad549d8ad24e6b27357e64

test:
  secret_key_base: 17c3530a482ada6cb7117d0cb17a8f1191d7106a7fc2917e3f6a41871642c5ec85f108296828d8f93913792ab49a2df7ce7ec7f198bdd51035cca66f042843ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
